image:
  file: .gitpod.Dockerfile
vscode: 
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliermarsh.ruff
    
tasks:
  - name: OpenAI interface
    command: pip install -r requirements.txt && python3 interactive-playground.py
  - name: Temporal Dev Server
    command:  temporal server start-dev